### Register a new user
POST https://kollabterm.fly.dev/auth/register
Content-Type: application/json

{
    "username": "LOL1",
    "password": "LOL"
}

### Login with the newly registered user
POST https://kollabterm.fly.dev/auth/login
Content-Type: application/json

{
    "username": "LOL1",
    "password": "LOL"
}
