### Register a new user
POST https://kollaboraatioterminaali.fly.dev/auth/register
Content-Type: application/json

{
    "username": "hihii",
    "password": ":3"
}

### Login with the newly registered user
POST https://kollaboraatioterminaali.fly.dev/auth/login
Content-Type: application/json

{
    "username": "hihii",
    "password": ":3"
}
